# Generated by Django 5.1 on 2024-08-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
