# Generated by Django 5.1 on 2024-08-25 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_remove_product_discount_product_discount_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMinSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_sum', models.CharField(max_length=255, verbose_name='min_order_sum')),
            ],
            options={
                'verbose_name': 'Order min sum',
                'verbose_name_plural': 'Order min sums',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('status', models.CharField(choices=[('created', 'Created'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=255, verbose_name='status')),
                ('phone_number', models.CharField(max_length=255, verbose_name='phone_number')),
                ('number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='order number')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='total price')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('is_visible', models.BooleanField(default=True, verbose_name='is_visible')),
                ('subtotal_price', models.FloatField(blank=True, null=True, verbose_name='subtotal price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='order.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
    ]
