# Generated by Django 5.1 on 2024-08-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='subtotal_price',
        ),
    ]
