# Generated by Django 5.1 on 2024-09-17 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_cartitem_subtotal_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subtotal_price',
            field=models.FloatField(blank=True, null=True, verbose_name='subtotal price'),
        ),
        migrations.CreateModel(
            name='NotificationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_count', models.PositiveIntegerField(default=0, verbose_name='employee count')),
                ('durations_days', models.PositiveIntegerField(default=0, verbose_name='durations days')),
                ('box_count', models.PositiveIntegerField(default=0, verbose_name='box count')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_orders', to='order.order', verbose_name='order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
